---
galaxy_info:
  role_name: ats_build
  author: frefur
  description: Builds Apache Traffic Server from source and archives artifact.
  company: NA
  galaxy_tags: [apache, trafficserver, ats, traffic, server]
  license: MIT

  min_ansible_version: 2.9

  platforms:
  - name: CentOS
    versions:
      - 7
      - 8

dependencies: []
