---
- name: Install Packages
  yum:
    name: "{{ item }}"
    state: installed
  loop: "{{ ats_core_packages }}"

- name: Create target directory
  file:
    mode: 0755
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ats_core_home | dirname }}"
    - "{{ ats_core_deploy_folder }}"

- name: Copy tar file from Control node 
  copy:
    src: "{{ ats_core_source_archive }}"
    dest: "{{ ats_core_deploy_folder }}/ats.tar.gz"
    mode: 0644
    owner: root
    group: root
  when: not ats_core_source_archive | urlsplit('scheme') in ['http','https']

- name: Copy tar file form Url
  get_url:
    url: "{{ ats_core_source_archive }}"
    dest: "{{ ats_core_deploy_folder }}/ats.tar.gz"
    username: "{{ ats_core_source_username | default(omit) }}"
    password: "{{ ats_core_source_password | default(omit) }}"
    checksum: "{{ ats_core_source_checksum | default(omit) }}"
    force: "{{ ats_core_source_force | default(omit) }}"
    mode: 0644
    owner: root
  when: ats_core_source_archive | urlsplit('scheme') in ['http','https']

- name: Extract tar file for deployment
  unarchive:
    src: "{{ ats_core_deploy_folder }}/ats.tar.gz"
    dest: "{{ ats_core_home | dirname }}"
    remote_src: true

- name: Include configuration conditionally
  include_tasks: configure.yml
  when: (ats_core_manage_config)

- name: Copy system start up file
  template:
    src: templates/trafficserver.service.j2
    dest: /usr/lib/systemd/system/trafficserver.service
    mode: 0644
    owner: root
    group: root
  register: ats_core_service_results

- name: Enable and Start service
  systemd:
    name: trafficserver
    state: "{{ ats_core_service_state }}"
    enabled: "{{ ats_core_service_enabled }}"
    daemon_reload: "{{ ats_core_service_results.changed | ternary('true', 'false') }}"
  register: ats_core_systemd_results

- name: Reload config exchange
  import_tasks: reload.yml
