---
ats_core_home: /opt/ats
ats_core_conf_inc_dir: "{{ ats_core_home }}/etc/trafficserver/conf.d"
ats_core_service_enabled: true
ats_core_manage_config: true
ats_core_purge_inc_dir: true
ats_core_service_state: started
ats_core_source_archive: files/ats-artifact-9.1.1.tar.gz
ats_core_cache_config:
  - dest_domain: mydomain.com
    suffix: gif
    revalidate: 6h

ats_core_splitdns_config:
  - dest_domain: internal.company.com
    named: 255.255.255.255:212 255.255.255.254
    def_domain: company.com
    search_list: company.com company1.com

ats_core_plugin_config:
  - name: plugins/abuse/abuse.so
    args: [etc/trafficserver/abuse.config]

# ats_core_records_config:
#   - scope: config
#     name: proxy.config.http.anonymize_remove_user_agent
#     type: int
#     value: 0

# ats_core_ip_allow:
#   ip_allow:
#     - apply: in
#       ip_addrs: 127.0.0.1
#       action: allow
#       methods: ALL
#     - apply: in
#       ip_addrs: ::1
#       action: allow
#       methods: ALL
#     - apply: in
#       ip_addrs: 0/0
#       action: deny
#       methods:
#         - PURGE
#         - PUSH
#         - DELETE
#     - apply: in
#       ip_addrs: ::/0
#       action: deny
#       methods:
#         - PURGE
#         - PUSH
#         - DELETE

ats_core_remap_config:
  - type: include
    files: [filters.config]

  - type: include
    files: [top.config, buttom.config]

  - type: map
    target: http://www.x.com/
    replace: http://server.hoster.com/
    acls:
      action: deny
      src_ip: 10.5.2.1
    plugins:
      - path: /etc/traffic_server/config/plugins/plugin1.so
        param: 1
        params: 2

  - type: map_with_referer
    client_url: http://y.foo.bar.com/x/yy/ 
    origin_server_url: http://foo.bar.com/x/yy/
    redirect_url: http://foo.bar.com/x/yy/
    regexes: ['.*\.bar\.com', 'www.bar-friends.com']

  - type: activatefilter
    name: deny_purge

  - type: definefilter
    name: deny_purge
    action: deny
    method: purge

ats_core_remap_includes:
  filters:
  - type: activatefilter
    name: deny_purge

  - type: definefilter
    name: deny_purge
    action: deny
    method: purge
